import React, { useEffect, useRef } from 'react';
import { Message } from '../types';
import MarkdownRenderer from './MarkdownRenderer';
import { User, AudioLines } from 'lucide-react';

interface MessageListProps {
  messages: Message[];
  isStreaming: boolean;
}

// Special "Neural Gem" Logo for Aira
const AiraLogo = ({ size = 24, className = "" }: { size?: number, className?: string }) => (
    <svg 
      xmlns="http://www.w3.org/2000/svg" 
      width={size} 
      height={size} 
      viewBox="0 0 24 24" 
      fill="none" 
      stroke="currentColor" 
      strokeWidth="1.5" 
      strokeLinecap="round" 
      strokeLinejoin="round" 
      className={className}
    >
      <path d="M12 22l-8.5-5V7L12 2l8.5 5v10L12 22z" />
      <path d="M12 22V12" />
      <path d="M12 12L3.5 7" />
      <path d="M12 12l8.5-5" />
      <path d="M12 2v5" />
      <path d="M3.5 7l5 3" />
      <path d="M20.5 7l-5 3" />
      <circle cx="12" cy="12" r="2" fill="currentColor" stroke="none" className="opacity-50" />
    </svg>
);

const MessageList: React.FC<MessageListProps> = ({ messages, isStreaming }) => {
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isStreaming]);

  if (messages.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-gray-100 px-4">
        <div className="bg-red-500/10 p-6 rounded-full mb-6 ring-1 ring-red-500/30 shadow-[0_0_15px_rgba(239,68,68,0.2)]">
           <AiraLogo size={64} className="text-red-500" />
        </div>
        <h2 className="text-2xl font-semibold mb-2">Aira</h2>
        <p className="text-gray-400 text-center max-w-md">
          Ask me anything, generate media, analyze videos, or talk live.
        </p>
      </div>
    );
  }

  return (
    <div className="flex-1 overflow-y-auto w-full scrollbar-thin scrollbar-thumb-gray-700">
      <div className="flex flex-col pb-32">
        {messages.map((message, index) => {
          const isUser = message.role === 'user';
          const isLast = index === messages.length - 1;
          const showCursor = isLast && isStreaming && !isUser;

          return (
            <div
              key={message.id}
              className={`
                w-full border-b border-black/10 
                ${isUser ? 'bg-[#343541]' : 'bg-[#444654]'}
              `}
            >
              <div className="max-w-3xl mx-auto px-4 py-8 flex gap-4 md:gap-6">
                <div className="shrink-0 flex flex-col relative items-end">
                  <div className={`w-8 h-8 rounded-sm flex items-center justify-center ${isUser ? 'bg-indigo-600' : 'bg-red-600 shadow-md shadow-red-900/20'}`}>
                    {isUser ? <User size={20} className="text-white" /> : <AiraLogo size={20} className="text-white" />}
                  </div>
                </div>

                <div className="relative flex-1 overflow-hidden">
                  <div className="font-semibold text-gray-100 mb-1 opacity-90 text-sm">
                    {isUser ? 'You' : 'Aira'}
                  </div>

                  {message.attachments && message.attachments.length > 0 && (
                    <div className="flex gap-2 mb-3 flex-wrap">
                      {message.attachments.map((att, i) => (
                         <div key={i} className="rounded-lg overflow-hidden border border-gray-600 bg-gray-800">
                            {att.mimeType.startsWith('image') ? (
                              <img src={`data:${att.mimeType};base64,${att.data}`} alt="attachment" className="h-32 object-cover" />
                            ) : (
                               <div className="h-16 px-4 flex items-center justify-center text-xs text-gray-300">
                                  {att.mimeType.split('/')[1].toUpperCase()} File
                                </div>
                            )}
                         </div>
                      ))}
                    </div>
                  )}
                  
                  {message.isError ? (
                     <div className="text-red-400 bg-red-900/20 p-3 rounded border border-red-900/50">{message.content}</div>
                  ) : (
                    <>
                      {message.generatedImage && (
                        <div className="mb-4">
                           <img src={message.generatedImage} alt="Generated by AI" className="rounded-lg max-h-[400px] w-auto border border-gray-600 shadow-lg" />
                        </div>
                      )}

                      {message.generatedVideo && (
                        <div className="mb-4">
                           <video controls src={message.generatedVideo} className="rounded-lg max-h-[400px] w-auto border border-gray-600 shadow-lg" />
                        </div>
                      )}

                      {message.audioData && (
                        <div className="mb-4 flex items-center gap-3 bg-gray-800 p-3 rounded-lg border border-gray-700">
                           <div className="bg-emerald-500/20 p-2 rounded-full"><AudioLines size={20} className="text-emerald-400" /></div>
                           <audio controls src={message.audioData} className="h-8 w-64" />
                        </div>
                      )}

                      {message.content && (
                        <div className={showCursor ? "typing-cursor" : ""}>
                          <MarkdownRenderer content={message.content} />
                        </div>
                      )}
                    </>
                  )}
                </div>
              </div>
            </div>
          );
        })}
        <div ref={bottomRef} />
      </div>
    </div>
  );
};

export default MessageList;